# Generated by Django 4.2.4 on 2023-08-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='file',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
