# Generated by Django 4.2.4 on 2023-08-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0002_remove_mediaitem_file_mediaitem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
