# Generated by Django 4.2.4 on 2023-08-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0004_portfolio_delete_mediaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Photographe.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10, verbose_name='Type de contenu'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
