# Generated by Django 4.2.4 on 2023-08-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0005_alter_portfolio_category_alter_portfolio_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Homereview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('review', models.TextField(verbose_name='Avis')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('review', models.TextField(max_length=1000, verbose_name='Avis')),
                ('time', models.CharField(max_length=100, verbose_name='Temps')),
                ('pictures_nb', models.CharField(max_length=100, verbose_name='Nombre de photos')),
                ('price', models.CharField(max_length=100, verbose_name='Prix')),
                ('inverse', models.BooleanField(default=False, verbose_name='Inversé ?')),
            ],
        ),
        migrations.CreateModel(
            name='Homeslide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Photographe.category', verbose_name='Catégorie')),
            ],
        ),
    ]
