# Generated by Django 4.2.4 on 2023-08-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0006_homecard_homereview_presentation_tarif_homeslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslide',
            name='category',
        ),
    ]
