# Generated by Django 4.2.4 on 2023-08-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0007_remove_homeslide_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='review',
        ),
        migrations.AddField(
            model_name='tarif',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
    ]
