# Generated by Django 4.2.4 on 2025-10-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0009_presentation_para_1_presentation_para_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie du contenu', 'verbose_name_plural': 'Catégories du contenu'},
        ),
        migrations.AlterModelOptions(
            name='homecard',
            options={'verbose_name': "Catégorie d'accueil", 'verbose_name_plural': "Catégorie d'accueil"},
        ),
        migrations.AlterModelOptions(
            name='homereview',
            options={'verbose_name': 'Avis Client', 'verbose_name_plural': 'Avis Clients'},
        ),
        migrations.AlterModelOptions(
            name='homeslide',
            options={'verbose_name': "Diaporama d'accueil", 'verbose_name_plural': "Diaporama d'accueil"},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Présentation', 'verbose_name_plural': 'Présentation'},
        ),
        migrations.AlterModelOptions(
            name='tarif',
            options={'verbose_name': 'Tarif', 'verbose_name_plural': 'Tarifs'},
        ),
    ]
