# Generated by Django 4.2.4 on 2025-10-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0010_alter_category_options_alter_homecard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Titre de la catégorie de photo', max_length=50),
        ),
    ]
