# Generated by Django 4.2.4 on 2025-10-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0011_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Portfolio - Catégorie', 'verbose_name_plural': 'Portfolio - Catégories'},
        ),
        migrations.AlterModelOptions(
            name='homecard',
            options={'verbose_name': 'Accueil - Catégorie', 'verbose_name_plural': 'Accueil - Catégories'},
        ),
        migrations.AlterModelOptions(
            name='homereview',
            options={'verbose_name': 'Accueil - Avis Client', 'verbose_name_plural': 'Accueil - Avis Clients'},
        ),
        migrations.AlterModelOptions(
            name='homeslide',
            options={'verbose_name': 'Accueil - Diaporama', 'verbose_name_plural': 'Accueil - Diaporama'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio - Contenu', 'verbose_name_plural': 'Portfolio -  Contenu'},
        ),
    ]
