# Generated by Django 4.2.4 on 2025-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photographe', '0012_alter_category_options_alter_homecard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Élément du portfolio', 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='file',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/videos/', verbose_name='Vidéo'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10, verbose_name='Type de média'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
    ]
